/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROCESY_H_RPCGEN
#define _PROCESY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char value[64];
};
typedef struct message message;

#define LAB2_PROGR 0x23451111
#define LAB2_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getMsg 1
extern  void * getmsg_1(message *, CLIENT *);
extern  void * getmsg_1_svc(message *, struct svc_req *);
extern int lab2_progr_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getMsg 1
extern  void * getmsg_1();
extern  void * getmsg_1_svc();
extern int lab2_progr_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROCESY_H_RPCGEN */
